/* // This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
}); */

import { createClient } from '@supabase/supabase-js';
import { mockSupabase } from '@/lib/mockSupabaseClient';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Enable mock mode during development
const USE_MOCK = import.meta.env.VITE_USE_MOCK === 'true';

let supabase: any;

if (USE_MOCK || !supabaseUrl || !supabaseAnonKey) {
  console.warn('🔧 Using MOCK DATABASE - No real data will be saved!');
  supabase = mockSupabase;
} else {
  supabase = createClient(supabaseUrl, supabaseAnonKey);
}

export { supabase };
